// The 18 Core Marketing Divisions, transcribed from "SOCIALxBRAND PILOT — Services & Divisions
// Master Document". Wording is the client's source of truth: edit only against that PDF.

export type ClusterId = "strategy-creative" | "performance-search" | "direct" | "growth-pr-ai";

export type Cluster = { id: ClusterId; name: string; short: string };

export const clusters: Cluster[] = [
  { id: "strategy-creative", name: "Strategy & Creative", short: "Strategy & Creative" },
  { id: "performance-search", name: "Performance & Search", short: "Performance & Search" },
  { id: "direct", name: "Direct Marketing", short: "Direct" },
  { id: "growth-pr-ai", name: "Growth, PR & AI", short: "Growth, PR & AI" },
];

export type CapabilityGroup = { title: string; items: string[] };

export type Division = {
  number: number;
  slug: string;
  name: string;
  shortName: string;
  cluster: ClusterId;
  whatItIs: string[];
  groups: CapabilityGroup[];
  deliverables: string[];
  approach: string[];
  /** Work screenings whose assets show this kind of capability (see content/work.ts). */
  relatedWork: string[];
  related: string[];
};

export const divisions: Division[] = [
  {
    number: 1,
    slug: "strategy-consulting",
    name: "Digital Marketing Strategy & Consulting",
    shortName: "Strategy & Consulting",
    cluster: "strategy-creative",
    whatItIs: [
      "Digital Marketing Strategy & Consulting helps businesses understand their current digital position, identify opportunities and challenges, define objectives and build strategic roadmaps aligned with business goals.",
      "We don't start with 'What should we post?' We start with: 'What does the business need to achieve?'",
    ],
    groups: [
      { title: "Digital Marketing Strategy", items: ["Complete digital marketing strategy", "Growth strategy", "Channel strategy", "Organic + paid strategy", "Short-term planning", "Long-term planning", "Digital growth roadmap"] },
      { title: "Marketing Audit & Analysis", items: ["Digital presence audit", "Social media audit", "Website audit", "Content audit", "Advertising audit", "SEO audit", "Competitor analysis", "Overall marketing audit"] },
      { title: "Market & Audience Research", items: ["Market research", "Target audience research", "Customer personas", "Audience segmentation", "Behaviour analysis", "Customer journey mapping", "Competitor analysis", "Market positioning"] },
      { title: "Campaign Strategy", items: ["Campaign planning", "Campaign objectives", "Audience strategy", "Channel selection", "Funnel planning", "Launch strategy", "Measurement framework"] },
      { title: "Go-To-Market Strategy", items: ["New brand launch", "Product launch", "Service launch", "Market entry", "Launch campaigns", "Digital roadmap"] },
      { title: "Business Applications", items: ["Understand current position", "Identify gaps and opportunities", "Define target audiences", "Define marketing objectives", "Select appropriate channels", "Prioritize resources", "Measure performance"] },
    ],
    deliverables: ["Marketing strategy", "Audit report", "Competitor analysis", "Audience research", "Customer personas", "Marketing roadmap", "Channel strategy", "Campaign strategy", "Funnel strategy", "Growth recommendations", "Action plan"],
    approach: ["Understand", "Analyze", "Strategize", "Plan", "Execute", "Measure", "Optimize", "Grow"],
    relatedWork: [],
    related: ["social-media-marketing", "performance-marketing", "branding-identity"],
  },
  {
    number: 2,
    slug: "social-media-marketing",
    name: "Social Media Marketing",
    shortName: "Social Media Marketing",
    cluster: "strategy-creative",
    whatItIs: [
      "Social Media Marketing is the strategic use of social platforms to build visibility, reach relevant audiences, create engagement, communicate value and support business growth.",
      "Our social media strategy is based on the business objective, audience, market, positioning and growth requirements.",
    ],
    groups: [
      { title: "Social Media Strategy", items: ["Social media marketing strategy", "Platform selection", "Platform-specific strategy", "Organic growth strategy", "Audience growth", "Engagement strategy", "Short-term planning", "Long-term growth planning"] },
      { title: "Social Media Campaigns", items: ["Campaign strategy", "Campaign planning", "Creative direction", "Audience targeting", "Awareness campaigns", "Engagement campaigns", "Lead-generation campaigns", "Product/service campaigns", "Seasonal campaigns"] },
      { title: "Audience & Community Growth", items: ["Target audience identification", "Audience segmentation", "Audience growth", "Engagement strategy", "Community growth", "Customer interaction", "Social listening", "Audience insights"] },
      { title: "Social Media Brand Building", items: ["Digital presence", "Brand communication", "Brand voice", "Visual direction", "Consistency", "Positioning", "Awareness", "Brand recall"] },
      { title: "Platforms", items: ["Instagram", "Facebook", "LinkedIn", "YouTube", "X", "Pinterest", "Snapchat", "Threads", "Telegram", "Reddit", "ShareChat", "Moj", "Josh", "Roposo"] },
    ],
    deliverables: ["Social media strategy", "Platform strategy", "Growth plan", "Campaign strategy", "Audience strategy", "Content strategy", "Content pillars", "Campaign concepts", "Performance insights"],
    approach: ["Business objective", "Audience", "Platforms", "Content", "Campaign", "Execution", "Measure", "Optimize"],
    relatedWork: ["creator-content", "restaurant-hospitality", "wedding-content"],
    related: ["social-media-management", "content-creation", "creator-brand-growth"],
  },
  {
    number: 3,
    slug: "social-media-management",
    name: "Social Media Management",
    shortName: "Social Media Management",
    cluster: "strategy-creative",
    whatItIs: [
      "Social Media Management focuses on the day-to-day planning, handling, publishing, monitoring and maintenance of a brand's social media presence.",
      "Management is not simply posting content. It involves planning + publishing + community + monitoring + analysis + optimization.",
    ],
    groups: [
      { title: "Account Management", items: ["Account management", "Profile optimization", "Account setup support", "Bio/profile information", "Platform coordination"] },
      { title: "Content Planning & Calendar", items: ["Monthly planning", "Content calendar", "Scheduling", "Distribution", "Content pillar implementation", "Campaign planning", "Festival planning"] },
      { title: "Content Publishing", items: ["Posts", "Reels", "Stories", "Carousels", "Short-form videos", "Scheduling", "Platform-specific publishing"] },
      { title: "Caption & Copy", items: ["Captions", "Social copy", "CTAs", "Hashtags", "Keywords", "Promotional copy", "Campaign copy", "Brand voice"] },
      { title: "Community Management", items: ["Comments", "DMs", "Audience interaction", "Customer query coordination", "Community engagement", "Response management", "Social listening"] },
      { title: "Analytics & Reporting", items: ["Monthly reports", "Reach analysis", "Engagement analysis", "Impression analysis", "Audience insights", "Growth tracking", "Content performance", "Recommendations"] },
    ],
    deliverables: ["Content calendar", "Scheduled content", "Published posts", "Published reels", "Captions", "Copy", "Hashtags/keywords", "Community management", "Analytics", "Reports"],
    approach: ["Plan", "Create", "Review & approve", "Schedule/publish", "Engage", "Monitor", "Measure", "Report", "Optimize"],
    relatedWork: ["restaurant-hospitality", "creator-content"],
    related: ["social-media-marketing", "content-marketing", "reputation-pr-community"],
  },
  {
    number: 4,
    slug: "content-marketing",
    name: "Content Marketing",
    shortName: "Content Marketing",
    cluster: "strategy-creative",
    whatItIs: [
      "Content Marketing is the strategic use of valuable, relevant and purposeful content to attract the right audience, build awareness and trust, support the customer journey and contribute to business growth.",
    ],
    groups: [
      { title: "Content Marketing Strategy", items: ["Content strategy", "Planning", "Goals and objectives", "Audience-based strategy", "Platform-based strategy", "Short-term planning", "Long-term planning", "Content distribution"] },
      { title: "Content Pillar & Topic Strategy", items: ["Content pillars", "Themes", "Topic research", "Topic clusters", "Content ideas", "Educational content", "Promotional content", "Engagement content", "Conversion content"] },
      { title: "Brand Storytelling", items: ["Brand narrative", "Founder stories", "Customer stories", "Product stories", "Brand values", "Story-led campaigns"] },
      { title: "Content Campaigns", items: ["Product launch", "Service launch", "Awareness", "Promotional", "Seasonal", "Festival", "Educational", "Brand campaigns"] },
      { title: "Content Distribution", items: ["Social media", "Website", "Blog", "Email", "WhatsApp", "Community", "Cross-platform distribution", "Content repurposing"] },
    ],
    deliverables: ["Content strategy", "Content plan", "Content pillars", "Calendar", "Topic bank", "Campaign strategy", "Storytelling framework", "Customer journey map", "Distribution plan", "SEO content strategy"],
    approach: ["Strategy", "Plan", "Create", "Distribute", "Measure", "Optimize"],
    relatedWork: ["stories-campaigns", "brand-films"],
    related: ["content-creation", "search-seo", "youtube-organic-video"],
  },
  {
    number: 5,
    slug: "content-creation",
    name: "Content Creation",
    shortName: "Content Creation",
    cluster: "strategy-creative",
    whatItIs: [
      "Content Creation is the development and production of original content that communicates a brand message, engages audiences, showcases products/services and supports marketing objectives.",
    ],
    groups: [
      { title: "Social Media Content", items: ["Instagram content", "Facebook content", "LinkedIn content", "Stories", "Reels", "Carousels", "Static posts", "Short-form videos", "Campaign content"] },
      { title: "Video Content", items: ["Reels", "Promotional videos", "Product videos", "Brand videos", "Explainer videos", "Educational videos", "Testimonials", "Interviews", "BTS", "Event content", "Lifestyle content"] },
      { title: "Script & Concept Development", items: ["Reel scripts", "Video scripts", "Ad scripts", "Explainer scripts", "Story concepts", "Campaign concepts", "Hooks", "CTAs", "Storyboards"] },
      { title: "Product & Service Content", items: ["Product showcase", "Product demonstrations", "Features", "Benefits", "Launch content", "Promotional content", "E-commerce content", "Catalogue content"] },
      { title: "UGC & Creator-Led Content", items: ["UGC-style content", "Creator content", "Reviews", "Demos", "Testimonials", "Creator-led reels", "Unboxing", "Social proof"] },
    ],
    deliverables: ["Concepts", "Scripts", "Reels", "Posts", "Carousels", "Stories", "Short-form videos", "Product content", "Brand content", "Campaign content", "Content series"],
    approach: ["Objective", "Audience", "Concept", "Script", "Production", "Post-production", "Adapt", "Distribute", "Learn"],
    relatedWork: ["creator-content", "restaurant-hospitality", "wedding-content", "automotive-moments"],
    related: ["video-production", "video-editing-animation", "creator-brand-growth"],
  },
  {
    number: 6,
    slug: "graphic-design",
    name: "Graphic Design",
    shortName: "Graphic Design",
    cluster: "strategy-creative",
    whatItIs: [
      "Graphic Design focuses on visual communication for brands, products, services, campaigns and marketing activities.",
      "Design is developed around the brand, objective, audience, platform and marketing requirement.",
    ],
    groups: [
      { title: "Social Media Design", items: ["Posts", "Carousels", "Stories", "Covers", "Profile graphics", "Highlight graphics", "Promotional creatives", "Educational creatives", "Festival/seasonal creatives"] },
      { title: "Advertising & Campaign Design", items: ["Digital ads", "Campaign visuals", "Promotional ads", "Offer creatives", "Product creatives", "Lead-generation creatives", "Awareness creatives", "Display visuals"] },
      { title: "Marketing Collateral", items: ["Brochures", "Flyers", "Leaflets", "Posters", "Banners", "Digital brochures", "Catalogues", "Company profiles", "Presentation decks", "Sales materials"] },
      { title: "Business & Corporate Design", items: ["Corporate presentations", "Company documents", "Proposals", "Pitch decks", "Reports", "Certificates", "Business cards", "Letterheads", "Email signatures"] },
      { title: "Infographics & Information Design", items: ["Infographics", "Data visualization", "Processes", "Educational graphics", "Comparisons", "Statistics", "Information cards", "Step-by-step visuals"] },
      { title: "Print & Promotional Design", items: ["Print-ready artwork", "Posters", "Flyers", "Brochures", "Outdoor advertising", "Event graphics", "Signage", "Merchandise graphics"] },
    ],
    deliverables: ["Social creatives", "Carousels", "Posters", "Flyers", "Brochures", "Banners", "Ads", "Presentations", "Pitch decks", "Infographics", "Product creatives", "Website graphics", "Thumbnails"],
    approach: ["Brief", "Concept", "Design", "Review", "Refine", "Deliver"],
    relatedWork: ["graphic-design", "logo-identity"],
    related: ["branding-identity", "creative-advertising-campaigns", "content-creation"],
  },
  {
    number: 7,
    slug: "video-production",
    name: "Video Production",
    shortName: "Video Production",
    cluster: "strategy-creative",
    whatItIs: [
      "Video Production covers the planning, production and capture of video content for brands, businesses, campaigns, products, services, events and digital platforms.",
    ],
    groups: [
      { title: "Pre-Production", items: ["Production planning", "Creative planning", "Concepts", "Scripts", "Storyboards", "Shot planning", "Location planning", "Talent/model coordination", "Scheduling", "Budget planning"] },
      { title: "Brand Video Production", items: ["Brand films", "Corporate videos", "Company profile videos", "Brand stories", "Founder videos", "About-us videos", "Culture videos", "Promotional videos"] },
      { title: "Commercial & Advertising", items: ["Commercials", "Digital ads", "Product ads", "Service ads", "Promotional videos", "Campaign videos", "Launch videos", "Social ads"] },
      { title: "Social Media Video", items: ["Reels", "Short-form videos", "Social campaigns", "Vertical videos", "Promotional videos"] },
      { title: "Corporate & Business", items: ["Corporate films", "Company videos", "Internal communication", "Training videos", "Business stories", "Leadership videos", "Founder videos", "Interviews"] },
      { title: "Event & Experience", items: ["Event videography", "Event highlights", "Recaps", "Brand activations", "Launches", "BTS", "Event promotions"] },
    ],
    deliverables: ["Concepts", "Scripts", "Storyboards", "Production plans", "Shoot production", "Raw footage", "Brand videos", "Commercials", "Product videos", "Social videos", "Interview videos", "Event videos"],
    approach: ["Concept", "Plan", "Pre-production", "Production", "Deliver"],
    relatedWork: ["brand-films", "wedding-films", "automotive-moments", "theatre-culture", "family-celebrations"],
    related: ["video-editing-animation", "photography", "youtube-organic-video"],
  },
  {
    number: 8,
    slug: "video-editing-animation",
    name: "Video Editing & Animation",
    shortName: "Video Editing & Animation",
    cluster: "strategy-creative",
    whatItIs: [
      "Video Editing & Animation is the post-production process of transforming raw footage, visuals, graphics and audio into polished, platform-ready video content.",
    ],
    groups: [
      { title: "Video Editing", items: ["Short-form videos", "Reels", "Social videos", "Long-form videos", "YouTube videos", "Corporate videos", "Commercials", "Product videos", "Interviews", "Testimonials", "Event videos", "Podcasts"] },
      { title: "Motion Graphics", items: ["Motion graphics", "Animated text", "Kinetic typography", "Lower thirds", "Titles", "Logo animation", "Infographic animation", "Visual callouts", "Transitions", "Branded motion"] },
      { title: "Animation", items: ["2D animation", "Explainer animation", "Character-based animation", "Typography animation", "Logo animation", "Product animation", "Educational animation", "Promotional animation"] },
      { title: "Audio", items: ["Audio editing", "Noise reduction", "Voice cleanup", "Sound effects", "Music", "Mixing", "Voice-over integration", "Audio synchronization"] },
      { title: "Captions", items: ["Subtitles", "Captions", "Animated captions", "Multilingual subtitles", "On-screen text", "Text storytelling"] },
      { title: "Repurposing", items: ["Long-form → Shorts", "YouTube → Reels", "Podcast → Clips", "Interviews → Short clips", "Platform adaptation", "Versioning"] },
    ],
    deliverables: ["Edited videos", "Reels", "Shorts", "YouTube videos", "Commercials", "Motion graphics", "Animation", "Logo animations", "Captioned videos", "Social cuts", "Video ads", "Repurposed content"],
    approach: ["Raw footage", "Editing plan", "Rough cut", "Creative/motion", "Audio/colour", "Captions", "QC", "Final"],
    relatedWork: ["wedding-films", "creator-content", "ai-content", "wedding-content"],
    related: ["video-production", "content-creation", "youtube-organic-video"],
  },
  {
    number: 9,
    slug: "photography",
    name: "Photography",
    shortName: "Photography",
    cluster: "strategy-creative",
    whatItIs: [
      "Photography creates high-quality visual assets that help businesses showcase their brand, products, services, people, spaces and experiences.",
      "We approach photography as a marketing asset, not simply as taking pictures.",
    ],
    groups: [
      { title: "Brand & Commercial Photography", items: ["Brand photography", "Commercial photography", "Brand story visuals", "Campaign photography", "Promotional photography", "Corporate brand visuals", "Founder photography"] },
      { title: "Product Photography", items: ["Product showcase", "Product features", "Product details", "Lifestyle product photography", "Product launches", "Catalogue photography", "E-commerce photography"] },
      { title: "Food & Beverage Photography", items: ["Food photography", "Beverage photography", "Restaurant photography", "Menu photography", "Food close-ups", "Lifestyle food photography", "Promotional food campaigns"] },
      { title: "Lifestyle Photography", items: ["Lifestyle shoots", "Product-in-use", "Customer experience", "People & environment", "Hospitality", "Fashion & lifestyle", "Travel & experience"] },
      { title: "Corporate & Business Photography", items: ["Company photography", "Team photography", "Office/workplace", "Corporate events", "Leadership", "Employee portraits", "Business activities"] },
      { title: "Event Photography", items: ["Corporate events", "Product launches", "Brand activations", "Workshops", "Conferences", "BTS", "Event highlights"] },
    ],
    deliverables: ["Edited photographs", "Product photographs", "Brand photographs", "Social media assets", "Campaign photographs", "Food/beverage photographs", "Corporate photographs", "Event photographs", "Catalogue images", "E-commerce images"],
    approach: ["Understand", "Plan", "Concept", "Shoot", "Select", "Edit", "Deliver", "Repurpose"],
    relatedWork: ["wedding-photography", "portrait-fashion", "family-celebrations"],
    related: ["video-production", "graphic-design", "content-creation"],
  },
  {
    number: 10,
    slug: "branding-identity",
    name: "Branding & Brand Identity",
    shortName: "Branding & Identity",
    cluster: "strategy-creative",
    whatItIs: [
      "Branding defines how a business is positioned, presented, communicated and remembered by its audience.",
      "Branding goes beyond a logo. It establishes the strategic, visual and communication foundations of a brand.",
    ],
    groups: [
      { title: "Brand Strategy", items: ["Brand strategy", "Brand positioning", "Brand purpose", "Vision", "Mission", "Values", "Personality", "Differentiation", "Target audience", "Brand perception", "Competitive positioning"] },
      { title: "Visual Brand Identity", items: ["Logo identity", "Logo variations", "Colour system", "Typography", "Visual language", "Graphic elements", "Iconography", "Imagery direction", "Layout principles"] },
      { title: "Logo Design", items: ["Logo concepts", "Primary logo", "Secondary logo", "Logo variations", "Symbol/mark", "Wordmark", "Icon", "Monogram", "Digital versions", "Print versions"] },
      { title: "Brand Voice & Messaging", items: ["Brand voice", "Tone of voice", "Messaging framework", "Communication style", "Key messages", "Taglines", "Brand statements", "Audience communication"] },
      { title: "Brand Guidelines", items: ["Logo usage", "Colour palette", "Typography", "Visual elements", "Photography direction", "Graphic style", "Brand voice", "Communication principles", "Do's & Don'ts"] },
      { title: "Rebranding", items: ["Brand audit", "Brand perception analysis", "Positioning review", "Visual refresh", "Logo refinement", "Messaging refresh", "Communication update", "Digital identity update", "Rebranding rollout"] },
    ],
    deliverables: ["Brand strategy", "Positioning framework", "Brand name", "Logo system", "Visual identity", "Colour palette", "Typography", "Brand voice", "Messaging framework", "Tagline", "Brand guidelines", "Social media identity"],
    approach: ["Discover", "Define", "Position", "Create", "Systemize", "Apply", "Launch", "Evolve"],
    relatedWork: ["logo-identity", "graphic-design"],
    related: ["graphic-design", "strategy-consulting", "creative-advertising-campaigns"],
  },
  {
    number: 11,
    slug: "creative-advertising-campaigns",
    name: "Creative Advertising & Campaigns",
    shortName: "Creative Campaigns",
    cluster: "strategy-creative",
    whatItIs: [
      "Creative Advertising & Campaigns turns a business objective into a strong creative marketing idea and coordinated campaign.",
      "A campaign is more than one post or advertisement. It is a connected marketing idea expressed through multiple touchpoints.",
    ],
    groups: [
      { title: "Campaign Ideation", items: ["Big campaign ideas", "Creative concepts", "Campaign themes", "Campaign narratives", "Story concepts", "Hooks", "Taglines", "Creative territories", "Campaign naming"] },
      { title: "Advertising Campaigns", items: ["Digital advertising concepts", "Promotional advertising", "Product advertising", "Brand advertising", "Awareness campaigns", "Engagement campaigns", "Lead-generation campaigns", "Conversion campaigns"] },
      { title: "Product & Service Campaigns", items: ["Product launches", "Service launches", "Product awareness", "Product promotion", "Feature/benefit campaigns", "Offer campaigns", "Customer acquisition campaigns"] },
      { title: "Launch Campaigns", items: ["Pre-launch", "Teaser campaigns", "Launch announcement", "Launch creative direction", "Launch content", "Post-launch communication"] },
      { title: "Seasonal & Festival Campaigns", items: ["Festival campaigns", "Seasonal campaigns", "Holiday campaigns", "Special-day campaigns", "Occasion campaigns", "Promotional campaigns"] },
      { title: "Creative Direction", items: ["Visual direction", "Photography direction", "Video direction", "Graphic direction", "Copy direction", "Content formats", "Creative consistency"] },
    ],
    deliverables: ["Campaign strategy", "Creative concept", "Big campaign idea", "Campaign theme", "Campaign name", "Campaign messaging", "Taglines", "Creative direction", "Campaign calendar", "Ad concepts", "Social campaign assets"],
    approach: ["Objective", "Insight", "Idea", "Strategy", "Creative", "Execution", "Measure", "Optimize"],
    relatedWork: ["stories-campaigns", "automotive-moments", "graphic-design"],
    related: ["performance-marketing", "content-creation", "branding-identity"],
  },
  {
    number: 12,
    slug: "performance-marketing",
    name: "Performance Marketing",
    shortName: "Performance Marketing",
    cluster: "performance-search",
    whatItIs: [
      "Performance Marketing uses paid digital advertising, measurable campaigns, audience targeting, tracking, testing and optimization to help businesses achieve defined objectives.",
      "Possible outcomes include: Reach, Traffic, Leads, Conversions, Sales, Customer acquisition, Return on advertising investment.",
    ],
    groups: [
      { title: "Meta Advertising", items: ["Facebook Ads", "Instagram Ads", "Campaign strategy", "Audience targeting", "Custom audiences", "Lookalike audiences", "Retargeting", "Lead generation", "Traffic", "Awareness", "Conversion", "Sales", "Creative testing", "Optimization"] },
      { title: "Google Ads", items: ["Search Ads", "Display Ads", "YouTube Ads", "Shopping campaigns", "Keyword targeting", "Audience targeting", "Remarketing", "Lead generation", "Conversion campaigns", "Campaign optimization"] },
      { title: "LinkedIn Advertising", items: ["LinkedIn strategy", "B2B advertising", "Professional audience targeting", "Lead generation", "Sponsored content", "Website traffic", "Retargeting", "Audience segmentation"] },
      { title: "Audience & Targeting", items: ["Target audience research", "Segmentation", "Demographic targeting", "Geographic targeting", "Interest targeting", "Behaviour targeting", "Custom audiences", "Lookalike audiences", "Retargeting"] },
      { title: "Lead Generation", items: ["Lead campaigns", "Lead forms", "Website lead campaigns", "WhatsApp campaigns", "Call campaigns", "Landing-page campaigns", "Lead funnel", "Lead quality analysis", "CPL optimization"] },
      { title: "Optimization", items: ["Budget optimization", "Audience optimization", "Creative optimization", "Placement optimization", "Cost optimization", "Conversion optimization", "Scaling opportunities"] },
    ],
    deliverables: ["Performance strategy", "Paid media plan", "Campaign structure", "Audience strategy", "Campaign setup", "Ad campaigns", "Retargeting", "Lead campaigns", "Testing framework", "Reports", "Optimization recommendations"],
    approach: ["Objective", "Audience", "Funnel", "Media plan", "Setup", "Launch", "Measure", "Test", "Optimize", "Scale"],
    relatedWork: [],
    related: ["search-seo", "creative-advertising-campaigns", "whatsapp-marketing"],
  },
  {
    number: 13,
    slug: "search-seo",
    name: "Search — SEO & Local SEO",
    shortName: "SEO & Local SEO",
    cluster: "performance-search",
    whatItIs: [
      "SEO improves a business's organic visibility in search engines so relevant audiences can discover its website, content, products, services or local business presence.",
      "Local SEO focuses specifically on location-based searches and local discovery.",
    ],
    groups: [
      { title: "SEO Audit", items: ["Website audit", "Technical audit", "On-page audit", "Content audit", "Keyword analysis", "Backlink analysis", "Competitor analysis", "Local SEO audit", "SEO gap analysis"] },
      { title: "Keyword Research", items: ["Keyword research", "Search volume analysis", "Search intent", "Short-tail keywords", "Long-tail keywords", "Local keywords", "Commercial keywords", "Product/service keywords", "Keyword mapping"] },
      { title: "On-Page SEO", items: ["Title tags", "Meta descriptions", "Heading structure", "URL optimization", "Internal linking", "Image optimization", "Content optimization", "Keyword placement", "Search-intent alignment"] },
      { title: "Technical SEO", items: ["Crawl analysis", "Indexing analysis", "Site structure", "XML sitemap", "Robots.txt", "Canonicalization", "Mobile usability", "Page experience", "Schema/structured-data direction"] },
      { title: "Local SEO", items: ["Local SEO strategy", "Local keywords", "Local search optimization", "Local citations", "Local competitor analysis", "Local visibility", "Review strategy", "Location-page strategy"] },
      { title: "Google Business Profile", items: ["Profile optimization", "Business information", "Category direction", "Description", "Services/products", "Photos/content direction", "Local optimization", "Review-response strategy", "Performance analysis"] },
    ],
    deliverables: ["SEO strategy", "SEO audit", "Keyword research", "Keyword map", "Competitor analysis", "On-page optimization", "Technical recommendations", "Content strategy", "Local SEO", "Google Business Profile optimization", "SEO reports"],
    approach: ["Audit", "Research", "Strategize", "Optimize", "Create", "Build", "Measure", "Improve"],
    relatedWork: [],
    related: ["content-marketing", "performance-marketing", "reputation-pr-community"],
  },
  {
    number: 14,
    slug: "whatsapp-marketing",
    name: "WhatsApp Marketing",
    shortName: "WhatsApp Marketing",
    cluster: "direct",
    whatItIs: [
      "WhatsApp Marketing uses WhatsApp as a direct communication and marketing channel for customers, prospects, leads and communities.",
      "It can support the customer journey from awareness and enquiries to follow-up, conversion and retention.",
    ],
    groups: [
      { title: "WhatsApp Business Setup", items: ["Business profile", "Business description", "Business hours", "Contact information", "Catalogue direction", "Quick replies", "Greeting messages", "Away messages", "Profile optimization"] },
      { title: "Broadcast Marketing", items: ["Broadcast campaigns", "Promotions", "Announcements", "Offers", "Festival campaigns", "Launches", "Updates", "Segmented broadcasts"] },
      { title: "Promotional Campaigns", items: ["Offers", "Discounts", "Launches", "Seasonal promotions", "Festival campaigns", "Limited-time campaigns", "Product announcements", "Re-engagement"] },
      { title: "Lead Generation", items: ["Click-to-WhatsApp", "Social-to-WhatsApp", "Website-to-WhatsApp", "Lead follow-up", "Lead qualification", "Customer communication"] },
      { title: "Automation & WhatsApp Business Platform", items: ["Automated responses", "Message workflows", "Customer journeys", "Lead routing", "FAQ automation", "Reminder workflows", "WhatsApp Business Platform/API direction", "CRM integration direction"] },
      { title: "Segmentation & Personalization", items: ["New customers", "Existing customers", "Leads", "High-intent prospects", "Repeat customers", "Inactive customers", "Product/service-specific audiences", "Location-based audiences"] },
    ],
    deliverables: ["WhatsApp strategy", "Business profile optimization", "Campaign strategy", "Broadcast plans", "Message templates", "Promotional campaigns", "Lead workflows", "Follow-up workflows", "Automation strategy", "WhatsApp funnel"],
    approach: ["Objective", "Audience", "Segment", "Message", "Distribute", "Engage", "Follow-up", "Measure", "Optimize"],
    relatedWork: [],
    related: ["performance-marketing", "ai-marketing-automation", "social-media-management"],
  },
  {
    number: 15,
    slug: "creator-brand-growth",
    name: "Creator / Brand Growth",
    shortName: "Creator / Brand Growth",
    cluster: "growth-pr-ai",
    whatItIs: [
      "Creator / Brand Growth uses creators, influencers and UGC to help brands reach relevant audiences, build credibility, create content and support growth.",
      "Creator selection is based on brand fit, audience relevance, campaign objective, content style and requirements — not simply follower count.",
    ],
    groups: [
      { title: "Creator Discovery & Selection", items: ["Creator research", "Influencer discovery", "Niche identification", "Audience relevance", "Content quality", "Engagement analysis", "Platform analysis", "Brand fit", "Shortlisting"] },
      { title: "Creator Categories", items: ["Nano creators", "Micro creators", "Mid-tier creators", "Macro creators", "Large-scale influencers", "Niche creators", "Local creators", "Industry experts"] },
      { title: "UGC Marketing", items: ["UGC strategy", "UGC creator discovery", "Product experiences", "Reviews", "Testimonials", "Unboxing", "Demonstrations", "Product-in-use", "Lifestyle content", "UGC-style ads", "Social proof"] },
      { title: "Creator–Brand Collaborations", items: ["Partnerships", "Product collaborations", "Sponsored content", "Campaign collaborations", "Long-term partnerships", "Ambassador programs", "Creator-led campaigns"] },
      { title: "Product Seeding", items: ["Creator identification", "Product seeding strategy", "Distribution coordination", "Creator briefs", "Follow-up", "Content collection", "Campaign tracking"] },
      { title: "Performance Tracking", items: ["Reach", "Impressions", "Views", "Engagement", "Likes", "Comments", "Shares", "Saves", "Link clicks", "Leads", "Conversions", "Creator performance"] },
    ],
    deliverables: ["Creator strategy", "Influencer strategy", "Creator shortlist", "Creator research", "Campaign concept", "Creator briefs", "UGC strategy", "UGC shortlist", "Content direction", "Product seeding strategy", "Performance reports"],
    approach: ["Objective", "Audience", "Creator", "Brief", "Collaborate", "Create", "Publish", "Measure", "Optimize"],
    relatedWork: ["creator-content"],
    related: ["content-creation", "social-media-marketing", "reputation-pr-community"],
  },
  {
    number: 16,
    slug: "youtube-organic-video",
    name: "YouTube & Organic Video Marketing",
    shortName: "YouTube & Video Marketing",
    cluster: "growth-pr-ai",
    whatItIs: [
      "YouTube & Organic Video Marketing uses YouTube and video content as long-term organic marketing channels to build awareness, authority, audience, community and business growth.",
      "The objective is not simply uploading videos. It is building a video ecosystem that attracts, engages and grows an audience.",
    ],
    groups: [
      { title: "YouTube Strategy", items: ["YouTube marketing strategy", "Channel growth strategy", "Content strategy", "Audience strategy", "Organic growth planning", "Long-term roadmap", "Distribution strategy", "KPIs"] },
      { title: "Content Strategy", items: ["Content pillars", "Themes", "Topic research", "Video ideas", "Series", "Content calendar", "Long-form strategy", "Shorts strategy", "Educational content", "Brand storytelling"] },
      { title: "YouTube SEO", items: ["Keyword research", "Search intent", "Topic optimization", "Titles", "Descriptions", "Metadata", "Hashtag direction", "Playlist optimization", "Search-focused planning"] },
      { title: "Thumbnail & Packaging", items: ["Thumbnail concepts", "Thumbnail direction", "Title + thumbnail strategy", "Visual hooks", "Packaging", "Testing direction"] },
      { title: "Organic Audience & Community", items: ["Audience research", "Subscriber growth", "Engagement", "Community interaction", "Comment engagement", "Community content", "Audience feedback", "Viewer insights"] },
      { title: "Video Distribution & Repurposing", items: ["YouTube → Shorts", "Shorts → Reels", "Reels → Facebook", "LinkedIn Clips", "Social Posts", "Content Assets"] },
    ],
    deliverables: ["YouTube strategy", "Channel strategy", "Channel optimization", "Content strategy", "Content pillars", "Topic research", "Video ideas", "Long-form strategy", "Shorts strategy", "YouTube SEO", "Thumbnail concepts", "Analytics reports", "Growth recommendations"],
    approach: ["Define", "Research", "Plan", "Create", "Optimize", "Publish", "Distribute", "Analyze", "Grow"],
    relatedWork: ["brand-films", "theatre-culture"],
    related: ["video-production", "video-editing-animation", "content-marketing"],
  },
  {
    number: 17,
    slug: "reputation-pr-community",
    name: "Reputation, PR & Community",
    shortName: "Reputation, PR & Community",
    cluster: "growth-pr-ai",
    whatItIs: [
      "Reputation, PR & Community focuses on managing and strengthening how a business is perceived, discussed and represented, while building meaningful relationships with audiences and relevant communities.",
    ],
    groups: [
      { title: "Online Reputation Management", items: ["Reputation strategy", "Reputation monitoring", "Brand mention monitoring", "Search-result reputation review", "Review monitoring", "Customer feedback", "Reputation analysis", "Improvement strategy"] },
      { title: "Reviews & Feedback", items: ["Review monitoring", "Review-response strategy", "Feedback analysis", "Positive feedback amplification", "Negative-feedback response direction", "Review-generation strategy", "Customer sentiment tracking"] },
      { title: "Reputation Recovery & Crisis Communication", items: ["Situation assessment", "Communication strategy", "Response planning", "Crisis messaging", "Social response direction", "Escalation planning", "Post-crisis analysis"] },
      { title: "Public Relations Strategy", items: ["PR strategy", "Brand communication", "Publicity planning", "Announcements", "Product/service announcements", "Launch communication", "Corporate communication", "Founder visibility", "PR campaigns"] },
      { title: "Digital PR", items: ["Online publication opportunities", "Digital media outreach", "Brand stories", "Expert positioning", "Thought leadership", "Digital announcements", "Brand features"] },
      { title: "Community Building", items: ["Community strategy", "Audience development", "Engagement planning", "Community content", "Discussion initiatives", "Audience interaction", "Loyalty initiatives"] },
    ],
    deliverables: ["Reputation strategy", "Reputation audit", "Review framework", "Social listening framework", "Brand monitoring", "Crisis communication framework", "PR strategy", "Digital PR strategy", "Community strategy", "Community management", "Reputation reports"],
    approach: ["Monitor", "Listen", "Understand", "Strategize", "Communicate", "Engage", "Measure", "Improve"],
    relatedWork: ["stories-campaigns"],
    related: ["social-media-management", "search-seo", "creator-brand-growth"],
  },
  {
    number: 18,
    slug: "ai-marketing-automation",
    name: "AI Marketing & AI Automation",
    shortName: "AI Marketing & Automation",
    cluster: "growth-pr-ai",
    whatItIs: [
      "AI Marketing & AI Automation uses artificial intelligence, automation technologies and intelligent workflows to improve marketing efficiency, content production, customer communication, data handling and repetitive business processes.",
      "AI is treated as a marketing and productivity layer supporting human strategy, creativity and execution.",
    ],
    groups: [
      { title: "AI Marketing Strategy", items: ["AI marketing strategy", "AI opportunity assessment", "Marketing workflow analysis", "AI tool selection", "AI implementation planning", "AI-assisted campaign workflows", "AI adoption roadmap"] },
      { title: "AI Content Ideation", items: ["Content ideas", "Campaign ideas", "Topic generation", "Content pillars", "Hooks", "Headlines", "Creative concepts", "Social media ideas", "Video ideas", "Content variations"] },
      { title: "AI-Assisted Copywriting", items: ["Social copy", "Ad copy", "Headlines", "Captions", "Product descriptions", "Website copy assistance", "Email copy", "WhatsApp copy", "Scripts", "CTA variations"] },
      { title: "AI Marketing Automation", items: ["Repetitive marketing workflows", "Content workflow automation", "Lead-routing workflows", "Customer communication workflows", "Notification workflows", "Data transfer workflows", "Reporting workflows", "Task automation"] },
      { title: "AI Chatbots & Conversational Workflows", items: ["FAQ chatbots", "Website conversational flows", "Lead qualification", "Customer enquiry routing", "Automated responses", "Knowledge-based assistance", "Conversational marketing workflows"] },
      { title: "Content Repurposing", items: ["Long Video → Shorts", "Shorts → Reels", "Reels → Posts", "Posts → Carousel", "Carousel → Blog", "Blog → Email", "Email → WhatsApp"] },
    ],
    deliverables: ["AI marketing strategy", "AI workflow audit", "AI implementation roadmap", "AI content workflows", "Automation workflows", "Lead automation", "Customer communication workflows", "Chatbot workflows", "Content repurposing systems", "Reporting automation", "Productivity workflows", "AI tool recommendations"],
    approach: ["Audit", "Identify", "Strategize", "Design", "Automate", "Test", "Implement", "Monitor", "Optimize"],
    relatedWork: ["ai-content"],
    related: ["whatsapp-marketing", "content-marketing", "strategy-consulting"],
  },
];

export const divisionBySlug = (slug: string) => divisions.find((d) => d.slug === slug);
export const pad = (n: number) => String(n).padStart(2, "0");
